### ISSUE TITLE
Fix texture to compatible with mipmaps lvl 4

### ISSUE THREAD

**Issue by anggerbudi** [AverageAnime/create-food-1.20.1#36]
Inside the mod, there is texture that if divided by 2 have a remainder (not zero). That makes the mipmap quality levels dropped from 4 which makes the quality of texture become bad in longer distance

**Comment by AverageAnime** [comment]
Fixed in 1.1.4.

**Comment by anggerbudi** [comment]
Please reopen this issue since the problem still showed in 1.1.4

`[04:05:11] [Worker-ResourceReload-5/WARN]: Texture createfood:item/icon with size 98x98 limits mip level from 4 to 1
[04:05:11] [Worker-ResourceReload-5/WARN]: minecraft:textures/atlas/blocks.png: dropping miplevel from 4 to 1, because of minimum power of two: 2`

[Logs](https://mclo.gs/xXJ4Clt)
